name: build and test feature branch
on: 
    push: 
        branches: 
            - feature/*
jobs:
    build-feature:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: pull and checkout from git repository
              run: |
                 echo "pulling and checkout from git repository"

            - uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '21'            